import type { Metadata } from "next";
import { Kantumruy_Pro, Montserrat, Urbanist } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { NavbarComponent } from "@/component/navbar/navbarcomponent";
// nextjs google fonts config
const kantumruy = Kantumruy_Pro({
  subsets: ['khmer'],
  weight: ['400', '700'],
  display: 'swap',
  variable: '--font-kantumruy',
});

// Local Fonts config
const plusjarkata = localFont({
  src: "../../public/fonts/PlusJakartaSans-SemiBold.ttf",
  variable: "--font-urbanist",
})

// const montserrat = Montserrat({
//   subsets: ['latin'],
//   weight: ['400', '700'],
//   display: 'swap',
//   variable: '--font-montserrat',
// });



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${kantumruy.variable} ${plusjarkata.variable} antialiased`}
      > 
        <NavbarComponent />
          {children}
      </body>
    </html>
  );
}
