import type { Metadata } from "next";
import { Kantumruy_Pro, Montserrat } from "next/font/google";
import "./globals.css";
import { NavbarComponent } from "@/component/navbar/navbarcomponent";

const kantumruy = Kantumruy_Pro({
  subsets: ['khmer'],
  weight: ['400', '700'],
  display: 'swap',
  variable: '--font-kantumruy',
});

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['400', '700'],
  display: 'swap',
  variable: '--font-montserrat',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${kantumruy.variable} ${montserrat.variable} antialiased`}
      >
        <NavbarComponent />
        {children}
      </body>
    </html>
  );
}
